source 'http://rubygems.org'

source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'sqlite3'
gem 'jquery-rails', '>= 0.2.7'
gem 'gravatar_image_tag'
gem 'will_paginate', '3.0.pre2'


group :development do
  gem 'rspec-rails'
  gem 'faker', '0.3.1'
end

group :test do
  gem 'rspec'
  gem 'webrat'
  gem 'spork'
  gem 'factory_girl_rails', '1.0'
end